#!/usr/bin/python3

import sys
import math


def prime_num(num):
    if num < 2:
        return False
    for j in range(2, int(math.sqrt(num)) + 1):
        if num % j == 0:
            return False
    return True


def factorize(n):
    for j in range(2, n):
        if n % j == 0 and prime_num(j) and prime_num(n // j):
            return j, n // j
    return None, None


def main(file_input):
    with open(file_input, 'r') as file:
        for line in file:
            n = int(line)
            p, q = factorize(n)
            if p is not None and q is not None:
                print(f"{n}={p}*{q}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_input = sys.argv[1]
    main(file_input)
